### ISSUE TITLE
Compatibilidad con Windows

### ISSUE THREAD

**Issue by juanjoabarca** [Pythoneiro/MQTT2MongoDB#1]
Hola, tu código me ayudó bastante, el problema es que quiero utilizarlo en Windows y tengo problemas con "signal" y "pause()", ¿Conoces alguna manera de adecuarlo?
Muchas gracias.

**Comment by David-Lor** [comment]
Hola,
me alegro de que te resultase útil. La verdad es que el código es bastante mejorable, pero no lo volví a tocar porque me pasé a otros backends para persistir los mensajes (actualmente uso InfluxDB + Telegraf).

Para el problema que comentas, posiblemente puedas reemplazar, en el archivo `__main__.py`, el `pause()` de la línea 12 por un `input()`, y borrar la línea 3 `from signal import pause`.

**Comment by juanjoabarca** [comment]
Perfecto, funcionó, muchas gracias!
